export default [
	{
		radius: 100,
		detail: 15,
		groundColor: '#23242F',
		waterColor: '#85DAF5',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.3,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/hoshimachi-suisei-gsap.png',
			rightImageSrc: '/img/projects/hoshimachi-suisei-gsap.png',
			mainImageSrc: '/img/projects/hoshimachi-suisei-gsap.png',
			title: 'Hoshimachi GSAP',
			description:
				'Practicing GSAP by creating a simple website for Hololive Member - Hoshimachi Suisei',
			viewUrl: 'https://djahvoe.github.io/hoshimachi-suisei-gsap/',
			githubUrl: 'https://github.com/DJahvoe/hoshimachi-suisei-gsap',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#60B028',
		waterColor: '#4AE6FF',
		atmosphereColor: '#00FFE0',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/portal.png',
			rightImageSrc: '/img/projects/portal.png',
			mainImageSrc: '/img/projects/portal.png',
			title: '3D Portal',
			description:
				'3D Portal built using THREE.js which is a library for building WebGL application, most of the object inside of the project is built using Blender',
			viewUrl: 'https://djahvoe.github.io/portal/',
			githubUrl: 'https://github.com/DJahvoe/portal',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#A456D4',
		waterColor: '#51ABDB',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/sound-board.png',
			rightImageSrc: '/img/projects/sound-board.png',
			mainImageSrc: '/img/projects/sound-board.png',
			title: 'Sound Board',
			description:
				'Experimental project to create something similar to Wave.js, an audio visualization library for JavaScript',
			viewUrl: 'https://djahvoe.github.io/sound-board/',
			githubUrl: 'https://github.com/DJahvoe/sound-board',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#000000',
		waterColor: '#582F8B',
		atmosphereColor: '#6D398D',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/canvas-sine-wave.png',
			rightImageSrc: '/img/projects/canvas-sine-wave.png',
			mainImageSrc: '/img/projects/canvas-sine-wave.png',
			title: 'Sine Wave',
			description:
				'Experimenting Canvas API by creating a simple animation using Sine function',
			viewUrl: 'https://djahvoe.github.io/canvas-sine-wave/',
			githubUrl: 'https://github.com/DJahvoe/canvas-sine-wave',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#1b3984',
		waterColor: '#f230ff',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/galaxy-three-js.png',
			rightImageSrc: '/img/projects/galaxy-three-js.png',
			mainImageSrc: '/img/projects/galaxy-three-js.png',
			title: 'Galaxy',
			description: 'Creating a galaxy object using library THREE.js',
			viewUrl: 'https://djahvoe.github.io/threejs-galaxy-generator/',
			githubUrl: 'https://github.com/DJahvoe/threejs-galaxy-generator',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#564436',
		waterColor: '#2472A7',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/storelogy.png',
			rightImageSrc: '/img/projects/storelogy.png',
			mainImageSrc: '/img/projects/storelogy.png',
			title: 'Storelogy API',
			description:
				'Internship project in Picodio that requires to migrate and creating a new endpoint for their marketplace services called Storelogy',
			viewUrl: 'https://redoc.picodio.co.id/',
			githubUrl: '',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#FF085D',
		waterColor: '#B1B1B1',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/japanese-pitch-accent-demo.png',
			rightImageSrc: '/img/projects/japanese-pitch-accent-demo.png',
			mainImageSrc: '/img/projects/japanese-pitch-accent-demo.png',
			title: 'Japanese Pitch Accent Demo',
			description:
				'A simple SPA to demonstrate the pitch-accent classification from Japanese language for Japanese beginner',
			viewUrl: 'https://djahvoe.github.io/japanese-pitch-accent-demo/',
			githubUrl: 'https://github.com/DJahvoe/japanese-pitch-accent-demo',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#213050',
		waterColor: '#9D65C9',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/sav-rtk.png',
			rightImageSrc: '/img/projects/sav-rtk.png',
			mainImageSrc: '/img/projects/sav-rtk.png',
			title: 'RTK Quiz',
			description:
				'Side project to create a quiz, based on Remembering the Kanji book',
			viewUrl: 'https://djahvoe.github.io/SavRTKQuiz/',
			githubUrl: 'https://github.com/DJahvoe/SavRTKQuiz',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#092A57',
		waterColor: '#6FC2D1',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/uruha-rushia.png',
			rightImageSrc: '/img/projects/uruha-rushia.png',
			mainImageSrc: '/img/projects/uruha-rushia.png',
			title: 'Uruha Rushia Opening',
			description:
				"Experimental project to create an animation using CSS and GSAP, to re-make the Hololive member's opening animation",
			viewUrl: 'https://djahvoe.github.io/Uruha-Rushia-Opening-Text/',
			githubUrl: 'https://github.com/DJahvoe/Uruha-Rushia-Opening-Text',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#42455B',
		waterColor: '#ffffff',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/sav-name.png',
			rightImageSrc: '/img/projects/sav-name.png',
			mainImageSrc: '/img/projects/sav-name.png',
			title: 'Sav Name',
			description:
				'Experimental project to create introduction animation using CSS-only',
			viewUrl:
				'https://djahvoe.github.io/DAY-X_WebProgrammingLog/DAY1_yui-remake/index.html',
			githubUrl:
				'https://github.com/DJahvoe/DAY-X_WebProgrammingLog/tree/master/DAY1_yui-remake',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#ffffff',
		waterColor: '#2389B6',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/webgl-rain.png',
			rightImageSrc: '/img/projects/webgl-rain.png',
			mainImageSrc: '/img/projects/webgl-rain.png',
			title: 'Rain',
			description:
				'Experimental project using Canvas API to create a rain animation',
			viewUrl: 'https://djahvoe.github.io/rain-shower/',
			githubUrl: 'https://github.com/DJahvoe/rain-shower/',
		},
	},
	{
		radius: 100,
		detail: 15,
		groundColor: '#ffffff',
		waterColor: '#1447E0',
		atmosphereColor: '#4c99ff',
		noiseConf: {
			noiseF: 0.015,
			noiseD: 15,
			noiseWaterTreshold: 0.4,
			noiseWaterLevel: 0.2,
		},
		userData: {
			leftImageSrc: '/img/projects/goldenautotech.jpg',
			rightImageSrc: '/img/projects/goldenautotech.jpg',
			mainImageSrc: '/img/projects/goldenautotech.jpg',
			title: 'Golden Autotech',
			description: 'Company website for Golden Autotech',
			viewUrl: 'http://www.gautotech.com/',
			githubUrl: '',
		},
	},
];
